typography_spectrum: 0.2730606582481414
color:
  brandStrength: 0.2930407817475498
  lightness: 0.4021563217975199
  saturation: 0.7619214719161391
  rhythmicContrast: 0.47619843389838934
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/829c5fde-58ec-47a3-ae1e-debedf8b556d.jpg
layout_spectrum: 0.33734297985211015
author:
  name: AnnaMarie
  email: photos@byannamarie.com
  url: ''
name: ByAnnaMarie
navigation:
  - name: Family Sessions
    id: 2b1ef08e-863e-4474-99ca-b3011709398c
    type: content
  - name: Newborn Sessions
    id: 1bb7e6df-ea68-461b-acea-f0a4f26e6687
    type: content
  - name: Maternity Sessions
    id: 286bb1b2-f5ed-4d5e-ba6a-21438d8d808e
    type: content
  - name: Mini Sessions
    id: 536b4817-b84d-4b8b-bc98-a6fefb65b230
    type: content
  - name: Beauty Sessions
    id: aa2f5945-17a3-4283-8637-c38ee46fb112
    type: content
title: 'AnnaMarie Photo AND Video '
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7fd7f1c-5eb3-4587-9d69-7f1a9c2e0a55.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/d7fd7f1c-5eb3-4587-9d69-7f1a9c2e0a55.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Portraits. Family.Weddings. Events
purpose:
  - type: contact
    url: 'mailto:Photos@byannamarie.com'
    label: Schedule your session~
